In [11]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import torch
from data_gen import data_gen
from iclib.core import init_seed, pt_init, pt_use_cuda, pt_device
from iclib.print_info import set_print, toggle_print, p_hb, p_he, p_ti

In [4]:
#pt_init()
pt_init(use_gpu=False)
print("CUDA:", pt_use_cuda())
print("DEVICE:", pt_device())

init_seed(42)
set_print(True)

CUDA: False
DEVICE: cpu:0


In [5]:
data = list(data_gen(num_words=11, batch_size=3, num_batches=2))
b = data[0]
b

In [6]:
print(b.src)
p_ti(b.src)
print(b.src_lengths)
p_ti(b.src_mask)

tensor([[ 4,  8,  5,  7, 10,  3,  7,  8,  5],
        [ 8,  8,  3,  6,  5,  2,  8,  6,  2],
        [ 1, 10,  6,  9,  1, 10,  3,  7,  4]])
dim: 2, size: [3, 9]
[9, 9, 9]
dim: 3, size: [3, 1, 9]


In [7]:
print(b.trg)
p_ti(b.trg)

print(b.trg_y)
p_ti(b.trg_y)

print(b.trg_lengths)
print(b.trg_mask)
p_ti(b.trg_mask)

tensor([[ 1,  4,  8,  5,  7, 10,  3,  7,  8],
        [ 1,  8,  8,  3,  6,  5,  2,  8,  6],
        [ 1,  1, 10,  6,  9,  1, 10,  3,  7]])
dim: 2, size: [3, 9]
tensor([[ 4,  8,  5,  7, 10,  3,  7,  8,  5],
        [ 8,  8,  3,  6,  5,  2,  8,  6,  2],
        [ 1, 10,  6,  9,  1, 10,  3,  7,  4]])
dim: 2, size: [3, 9]
[10, 10, 10]
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)
dim: 2, size: [3, 9]


In [8]:
print(b.nseqs)
print(b.ntokens)

3
27
